import { Task } from "../types/task.type";

export const MOCKED_TASKS: Task[] = [
  {
    id: 1,
    name: "Task 1",
    description: "Description 1",
    category: "Category 1",
    priority: 4,
    datetime: new Date("2020-01-01 00:00:00"),
    status: "completed",
  },
  {
    id: 2,
    name: "Task 2",
    description: "Description 2",
    category: "Category 2",
    priority: 8,
    datetime: new Date("2020-02-02 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 3,
    name: "Task 3",
    description: "Description 3",
    category: "Category 3",
    priority: 10,
    datetime: new Date("2020-03-03 00:00:00"),
    status: "completed",
  },
  {
    id: 4,
    name: "Task 4",
    description: "Description 4",
    category: "Category 4",
    priority: 1,
    datetime: new Date("2020-04-04 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 5,
    name: "Task 5",
    description: "Description 5",
    category: "Category 5",
    priority: 2,
    datetime: new Date("2020-05-05 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 6,
    name: "Task 6",
    description: "Description 6",
    category: "Category 6",
    priority: 5,
    datetime: new Date("2020-06-06 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 7,
    name: "Task 7",
    description: "Description 7",
    category: "Category 7",
    priority: 9,
    datetime: new Date("2020-07-07 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 8,
    name: "Task 8",
    description: "Description 8",
    category: "Category 8",
    priority: 3,
    datetime: new Date("2020-08-08 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 9,
    name: "Task 9",
    description: "Description 9",
    category: "Category 9",
    priority: 7,
    datetime: new Date("2020-09-09 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 10,
    name: "Task 10",
    description: "Description 10",
    category: "Category 10",
    priority: 6,
    datetime: new Date("2020-10-10 00:00:00"),
    status: "uncompleted",
  },
  {
    id: 11,
    name: "Task 11",
    description: "Description 11",
    category: "Category 11",
    priority: 9,
    datetime: new Date("2020-11-11 00:00:00"),
    status: "completed",
  },
];
